### ISSUE TITLE
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path

### ISSUE THREAD

**Issue by s13o** [Riskified/java_sdk#27]
There is an exception at com.riskified.RiskifiedClient.checkoutOrder(RiskifiedClient.java:130) we getting time to time
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
  	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
  	at com.google.gson.Gson.fromJson(Gson.java:887)
 	at com.google.gson.Gson.fromJson(Gson.java:852)
  	at com.google.gson.Gson.fromJson(Gson.java:801)
  	at com.google.gson.Gson.fromJson(Gson.java:773)
  	at com.riskified.RiskifiedClient.getCheckoutResponseObject(RiskifiedClient.java:553)
  	at com.riskified.RiskifiedClient.postCheckoutOrder(RiskifiedClient.java:496)
  	at com.riskified.RiskifiedClient.checkoutOrder(RiskifiedClient.java:130)
  .....
```
And there is no way to find what exactly the server has answered.
We need to improve exception handling for such cases.

**Comment by mooseriskified** [comment]
resolved a while ago, so we will close it. Let me know if you still having issues
